jobs:
  - name: jobvmanifest1
    type: manifest
    steps:
      - GET: resourcevtest-image1
      - GET: resourcevtest-dockeroption1
      - GET: resourcevtest-param1
      
  - name: jobvmanifest2
    type: manifest
    steps:
      - GET: resourcevtest-replica1
      - GET: resourcevtest-image2
      - GET: resourcevtest-dockeroption1
      
  - name: jobvmanifest3
    type: manifest
    steps:
      - GET: jobvmanifest1
      - GET: jobvmanifest2
