triggers:
  - name: triggerup1
    type: trigger
    pointer:
      message: 'test triggering for jobs.yml'
      
  - name: triggerup2
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerup3
    type: trigger
    pointer:
      counter: 1
